@@ .. @@
 import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';
 import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
-import { AuthProvider } from './src/contexts/AuthContext';
-import { Header } from './components/Header';
-import { Hero } from './components/Hero';
-import { Categories } from './components/Categories';
-import { FeaturedProducts } from './components/FeaturedProducts';
-import { Offers } from './components/Offers';
-import { Services } from './components/Services';
-import { Newsletter } from './components/Newsletter';
-import { Footer } from './components/Footer';
-import { Login } from './src/components/auth/Login';
-import { Signup } from './src/components/auth/Signup';
-import { Account } from './src/components/account/Account';
-import { ProtectedRoute } from './src/components/auth/ProtectedRoute';
-import { ProductsList } from './src/components/products/ProductsList';
-import { AdminDashboard } from './src/components/admin/AdminDashboard';
-import { AboutUs } from './src/components/pages/AboutUs';
-import { Services as ServicesPage } from './src/components/pages/Services';
-import { Blog } from './src/components/pages/Blog';
-import { ContactUs } from './src/components/pages/ContactUs';
-import { Chatbot } from './src/components/chatbot/Chatbot';
+import { AuthProvider } from './src/contexts/AuthContext';
+import { Header } from './src/components/layout/Header';
+import { Hero } from './src/components/features/home/Hero';
+import { Categories } from './src/components/features/home/Categories';
+import { FeaturedProducts } from './src/components/features/home/FeaturedProducts';
+import { Offers } from './src/components/features/home/Offers';
+import { Services } from './src/components/features/home/Services';
+import { Newsletter } from './src/components/features/home/Newsletter';
+import { Footer } from './src/components/layout/Footer';
+import { Login } from './src/components/features/auth/Login';
+import { Signup } from './src/components/features/auth/Signup';
+import { Account } from './src/components/features/account/Account';
+import { ProtectedRoute } from './src/components/features/auth/ProtectedRoute';
+import { ProductsList } from './src/components/features/products/ProductsList';
+import { AdminDashboard } from './src/components/features/admin/AdminDashboard';
+import { AboutUs } from './src/components/pages/AboutUs';
+import { Services as ServicesPage } from './src/components/pages/Services';
+import { Blog } from './src/components/pages/Blog';
+import { ContactUs } from './src/components/pages/ContactUs';
+import { Chatbot } from './src/components/features/chatbot/Chatbot';